# Generated by Django 2.0.13 on 2020-07-29 14:32

from django.db import migrations, models
import sub_cafi.models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_cafi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='pic',
            field=models.FileField(blank=True, null=True, storage=sub_cafi.models.OverWriteImg(), upload_to=''),
        ),
    ]
